Added mypy to this repo. (#16)
I still get an error for the `mqt.ddsim` import and do not really
understand why it is there, since `mqt.ddsim` is both listed as an
additional dependency in the `pre-commit-config.yaml` and also excluded
in the `pyproject.toml`. I would have assumed, that either of those two
options should resolve the problem:

```
error: Module "mqt" has no attribute "ddsim" 
[attr-defined]
    from mqt import ddsim
```

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: Lukas Burgholzer <lukas.burgholzer@jku.at>